#include "lockfile.hpp"

#include <cstdint>
#include <fstream>
#include <sstream>
#include <stdexcept>

namespace zlpkg {
namespace {

std::string trim(const std::string& s) {
    size_t start = s.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) return "";
    size_t end = s.find_last_not_of(" \t\r\n");
    return s.substr(start, end - start + 1);
}

// Field values (paths, urls, shas) may contain backslashes (Windows paths)
// and, adversarially, double quotes or newlines - all are escaped so every
// value round-trips exactly. An unescaped quote would otherwise let one
// field swallow the rest of its line, and a raw newline (legal in a Unix
// path) would inject whole new lock lines on re-read.
std::string quote(const std::string& s) {
    std::string out = "\"";
    for (char c : s) {
        if (c == '\\' || c == '"') {
            out += '\\';
            out += c;
        } else if (c == '\n') {
            out += '\\';
            out += 'n';
        } else if (c == '\r') {
            out += '\\';
            out += 'r';
        } else if (c == '\t') {
            out += '\\';
            out += 't';
        } else {
            out += c;
        }
    }
    out += '"';
    return out;
}

std::string unquote(const std::string& s, const std::filesystem::path& lockPath, int lineNo) {
    std::string t = trim(s);
    if (t.size() < 2 || t.front() != '"' || t.back() != '"') {
        throw std::runtime_error(lockPath.string() + ":" + std::to_string(lineNo) +
                                  ": expected a quoted string, got '" + t + "'");
    }
    std::string body = t.substr(1, t.size() - 2);
    // The writer only emits \\ and \" - but older locks predate escaping
    // (a Windows dir like C:\lib holds a raw backslash), and those must
    // still parse so the staleness check can re-resolve them instead of
    // dying in the parser. Unknown escapes therefore degrade to the char
    // itself, and a trailing lone backslash is kept literally.
    std::string out;
    for (size_t i = 0; i < body.size(); ++i) {
        if (body[i] == '\\' && i + 1 < body.size()) {
            char next = body[i + 1];
            if (next == 'n') out += '\n';
            else if (next == 'r') out += '\r';
            else if (next == 't') out += '\t';
            else out += next;
            ++i;
            continue;
        }
        out += body[i];
    }
    return out;
}

void hashMix(uint64_t& h, const std::string& s) {
    for (unsigned char c : s) {
        h ^= static_cast<uint64_t>(c);
        h *= 1099511628211ULL;
    }
    h ^= 0xFFULL; // field separator so ("ab","c") != ("a","bc")
    h *= 1099511628211ULL;
}

} // namespace

void hashDeps(uint64_t& h, const Manifest& manifest) {
    for (const auto& dep : manifest.dependencies) {
        hashMix(h, dep.name);
        hashMix(h, dep.kind == Dependency::Kind::Git ? "git" : "path");
        hashMix(h, dep.source);
        hashMix(h, dep.ref);
        hashMix(h, dep.version);
    }
}

std::string hexHash(uint64_t h) {
    std::ostringstream oss;
    oss << std::hex << h;
    return oss.str();
}

std::string lockManifestFingerprint(const Manifest& manifest) {
    uint64_t h = 14695981039346656037ULL;
    hashMix(h, manifest.name);
    hashMix(h, manifest.version);
    hashDeps(h, manifest);
    return hexHash(h);
}

std::string lockDepsFingerprint(const Manifest& manifest) {
    uint64_t h = 14695981039346656037ULL;
    hashDeps(h, manifest);
    return hexHash(h);
}

void writeLockFile(const std::filesystem::path& lockPath, const std::vector<ResolvedDependency>& deps,
                   const std::string& manifestSha) {
    std::ofstream out(lockPath, std::ios::trunc);
    if (!out) throw std::runtime_error("cannot write lock file '" + lockPath.string() + "'");

    out << "# zlpkg.lock - generated by `zlpkg install`. Do not edit by hand.\n"
           "# Run `zlpkg install --update` to re-resolve and rewrite this file.\n";

    out << "\n[meta]\n";
    out << "version = " << quote("1") << "\n";
    out << "manifest_sha = " << quote(manifestSha) << "\n";

    for (const auto& d : deps) {
        out << "\n[dependency." << d.name << "]\n";
        out << "kind = " << quote(d.kind == Dependency::Kind::Git ? "git" : "path") << "\n";
        out << "source = " << quote(d.source) << "\n";
        out << "ref = " << quote(d.resolvedRef) << "\n";
        out << "package_version = " << quote(d.packageVersion) << "\n";
        out << "deps_sha = " << quote(d.depsFingerprint) << "\n";
        if (!d.declaredRef.empty()) out << "declared_ref = " << quote(d.declaredRef) << "\n";
        out << "dir = " << quote(d.dir.string()) << "\n";
    }
}

LockFile readLockFile(const std::filesystem::path& lockPath) {
    std::ifstream in(lockPath);
    if (!in) throw std::runtime_error("cannot open lock file '" + lockPath.string() + "'");

    LockFile lock;
    ResolvedDependency* current = nullptr;
    bool inMeta = false;
    std::string rawLine;
    int lineNo = 0;

    while (std::getline(in, rawLine)) {
        ++lineNo;
        std::string line = trim(rawLine);
        if (line.empty() || line.front() == '#') continue;

        if (line.front() == '[' && line.back() == ']') {
            std::string section = line.substr(1, line.size() - 2);
            const std::string prefix = "dependency.";
            if (section == "meta") {
                inMeta = true;
                current = nullptr;
                continue;
            }
            if (section.rfind(prefix, 0) != 0) {
                throw std::runtime_error(lockPath.string() + ":" + std::to_string(lineNo) +
                                          ": unexpected section '[" + section + "]'");
            }
            inMeta = false;
            lock.deps.emplace_back();
            lock.deps.back().name = section.substr(prefix.size());
            current = &lock.deps.back();
            continue;
        }

        size_t eq = line.find('=');
        if (eq == std::string::npos) {
            throw std::runtime_error(lockPath.string() + ":" + std::to_string(lineNo) + ": expected 'key = value'");
        }
        std::string key = trim(line.substr(0, eq));
        std::string value = unquote(line.substr(eq + 1), lockPath, lineNo);

        if (inMeta) {
            if (key == "version") {
                if (value != "1") {
                    throw std::runtime_error(lockPath.string() + ":" + std::to_string(lineNo) +
                                              ": unsupported lockfile version '" + value +
                                              "' - regenerate with a newer zlpkg");
                }
            } else if (key == "manifest_sha") {
                lock.manifestSha = value;
            }
            // Unknown [meta] keys are ignored for forward compatibility.
            continue;
        }

        if (!current) {
            throw std::runtime_error(lockPath.string() + ":" + std::to_string(lineNo) +
                                      ": key found before any [meta] or [dependency.<name>] section");
        }

        if (key == "kind") current->kind = (value == "git") ? Dependency::Kind::Git : Dependency::Kind::Path;
        else if (key == "source") current->source = value;
        else if (key == "ref") current->resolvedRef = value;
        else if (key == "package_version") current->packageVersion = value;
        else if (key == "deps_sha") current->depsFingerprint = value;
        else if (key == "declared_ref") current->declaredRef = value;
        else if (key == "dir") current->dir = value;
        // Unknown keys are ignored, same forward-compatibility reasoning
        // as unknown [package] keys in the manifest parser.
    }

    return lock;
}

} // namespace zlpkg
