#pragma once
// zlpkg.lock: records exactly what `zlpkg install` resolved, so a later
// install (on this machine or a teammate's) reproduces the identical set
// of dependencies without re-running the resolver - `zlpkg install` reuses
// the lock as-is whenever one exists, and only re-resolves when asked to
// (`zlpkg install --update`) or when the lock is missing entirely.
//
// The file is valid TOML (a person can read it, even though nothing reads
// it besides zlpkg itself), shaped as one [dependency.<name>] table per
// resolved dependency:
//
//   # zlpkg.lock - generated by `zlpkg install`. Do not edit by hand.
//
//   [dependency.geom]
//   kind = "path"
//   source = "../geom"
//   ref = "local"
//   dir = "/abs/path/to/geom"
//
//   [dependency.ecs]
//   kind = "git"
//   source = "https://example.com/zl-ecs.git"
//   ref = "8f3a1c9d2e4b5a6f7c8d9e0f1a2b3c4d5e6f7a8b"
//   declared_ref = "v1.0.0"
//   dir = "/abs/path/to/project/.zlpkg/ecs/8f3a1c9d2e4b5a6f7c8d9e0f1a2b3c4d5e6f7a8b"

#include <filesystem>
#include <vector>

#include "resolver.hpp"

namespace zlpkg {

void writeLockFile(const std::filesystem::path& lockPath, const std::vector<ResolvedDependency>& deps);

// Throws ManifestError-style std::runtime_error on a malformed lock file.
std::vector<ResolvedDependency> readLockFile(const std::filesystem::path& lockPath);

} // namespace zlpkg
