#pragma once
// zlpkg.lock: records exactly what `zlpkg install` resolved, so a later
// install (on this machine or a teammate's) reproduces the identical set
// of dependencies without re-running the resolver.
//
// The lock is a CACHE, not an authority: it is only reused after being
// validated against the current manifest (see ensureInstalled in
// commands.cpp). The manifest is authoritative for every declaration
// (which deps exist, their kind/source/ref); the lock contributes only
// the resolved pins (git shas). Anything that fails validation - a
// manifest edit, a tampered entry, a missing directory - makes the lock
// stale, and a stale lock is simply re-resolved and rewritten, exactly
// as if it were missing. A lock whose syntax itself is corrupt is a hard
// error rather than a silent re-resolve, matching ecosystem behavior.
//
// The file is valid TOML (a person can read it, even though nothing reads
// it besides zlpkg itself): one [meta] table carrying the format version
// and a fingerprint of the manifest it was resolved from, then one
// [dependency.<name>] table per resolved dependency:
//
//   # zlpkg.lock - generated by `zlpkg install`. Do not edit by hand.
//
//   [meta]
//   version = "1"
//   manifest_sha = "9f2ac41b7e03d5aa"
//
//   [dependency.geom]
//   kind = "path"
//   source = "../geom"
//   ref = "local"
//   dir = "/abs/path/to/geom"
//
//   [dependency.ecs]
//   kind = "git"
//   source = "https://example.com/zl-ecs.git"
//   ref = "8f3a1c9d2e4b5a6f7c8d9e0f1a2b3c4d5e6f7a8b"
//   declared_ref = "v1.0.0"
//   dir = "/abs/path/to/project/.zlpkg/ecs/8f3a1c9d2e4b5a6f7c8d9e0f1a2b3c4d5e6f7a8b"

#include <filesystem>
#include <string>
#include <vector>

#include "resolver.hpp"

namespace zlpkg {

struct LockFile {
    // Fingerprint of the manifest this lock was resolved from; empty when
    // the lock predates fingerprinting (treated as stale on load).
    std::string manifestSha;
    std::vector<ResolvedDependency> deps;
};

// FNV-1a/64 (hex) over the manifest's semantic content: package name and
// version plus, per dependency, name/kind/source/ref/version-pin. Raw
// bytes are deliberately NOT hashed, so comment and whitespace edits do
// not invalidate the lock and trigger a spurious (network-touching)
// re-resolve.
std::string lockManifestFingerprint(const Manifest& manifest);

void writeLockFile(const std::filesystem::path& lockPath, const std::vector<ResolvedDependency>& deps,
                   const std::string& manifestSha);

// Throws ManifestError-style std::runtime_error on a malformed lock file,
// or when the lock's format version is newer than this zlpkg understands
// (fail closed: an unknown lock shape must never be trusted).
LockFile readLockFile(const std::filesystem::path& lockPath);

} // namespace zlpkg
