#include "lockfile.hpp"

#include <fstream>
#include <stdexcept>

namespace zlpkg {
namespace {

std::string trim(const std::string& s) {
    size_t start = s.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) return "";
    size_t end = s.find_last_not_of(" \t\r\n");
    return s.substr(start, end - start + 1);
}

std::string quote(const std::string& s) {
    // Field values here (paths, urls, shas, "local") never contain a
    // double quote in practice, so a straight wrap is sufficient.
    return "\"" + s + "\"";
}

std::string unquote(const std::string& s, const std::filesystem::path& lockPath, int lineNo) {
    std::string t = trim(s);
    if (t.size() < 2 || t.front() != '"' || t.back() != '"') {
        throw std::runtime_error(lockPath.string() + ":" + std::to_string(lineNo) +
                                  ": expected a quoted string, got '" + t + "'");
    }
    return t.substr(1, t.size() - 2);
}

} // namespace

void writeLockFile(const std::filesystem::path& lockPath, const std::vector<ResolvedDependency>& deps) {
    std::ofstream out(lockPath, std::ios::trunc);
    if (!out) throw std::runtime_error("cannot write lock file '" + lockPath.string() + "'");

    out << "# zlpkg.lock - generated by `zlpkg install`. Do not edit by hand.\n"
           "# Run `zlpkg install --update` to re-resolve and rewrite this file.\n";

    for (const auto& d : deps) {
        out << "\n[dependency." << d.name << "]\n";
        out << "kind = " << quote(d.kind == Dependency::Kind::Git ? "git" : "path") << "\n";
        out << "source = " << quote(d.source) << "\n";
        out << "ref = " << quote(d.resolvedRef) << "\n";
        out << "package_version = " << quote(d.packageVersion) << "\n";
        if (!d.declaredRef.empty()) out << "declared_ref = " << quote(d.declaredRef) << "\n";
        out << "dir = " << quote(d.dir.string()) << "\n";
    }
}

std::vector<ResolvedDependency> readLockFile(const std::filesystem::path& lockPath) {
    std::ifstream in(lockPath);
    if (!in) throw std::runtime_error("cannot open lock file '" + lockPath.string() + "'");

    std::vector<ResolvedDependency> deps;
    ResolvedDependency* current = nullptr;
    std::string rawLine;
    int lineNo = 0;

    while (std::getline(in, rawLine)) {
        ++lineNo;
        std::string line = trim(rawLine);
        if (line.empty() || line.front() == '#') continue;

        if (line.front() == '[' && line.back() == ']') {
            std::string section = line.substr(1, line.size() - 2);
            const std::string prefix = "dependency.";
            if (section.rfind(prefix, 0) != 0) {
                throw std::runtime_error(lockPath.string() + ":" + std::to_string(lineNo) +
                                          ": unexpected section '[" + section + "]'");
            }
            deps.emplace_back();
            deps.back().name = section.substr(prefix.size());
            current = &deps.back();
            continue;
        }

        if (!current) {
            throw std::runtime_error(lockPath.string() + ":" + std::to_string(lineNo) +
                                      ": key found before any [dependency.<name>] section");
        }

        size_t eq = line.find('=');
        if (eq == std::string::npos) {
            throw std::runtime_error(lockPath.string() + ":" + std::to_string(lineNo) + ": expected 'key = value'");
        }
        std::string key = trim(line.substr(0, eq));
        std::string value = unquote(line.substr(eq + 1), lockPath, lineNo);

        if (key == "kind") current->kind = (value == "git") ? Dependency::Kind::Git : Dependency::Kind::Path;
        else if (key == "source") current->source = value;
        else if (key == "ref") current->resolvedRef = value;
        else if (key == "package_version") current->packageVersion = value;
        else if (key == "declared_ref") current->declaredRef = value;
        else if (key == "dir") current->dir = value;
        // Unknown keys are ignored, same forward-compatibility reasoning
        // as unknown [package] keys in the manifest parser.
    }

    return deps;
}

} // namespace zlpkg
